
COMMON: &common

  # A string for security. It is used to sign tokens
  app_secret: O\xa9\x81\xae\xf5\x83\xe7[\xcc\xfcS\x8a\r\xd3T\x97\x0c\xbf\xeb0\xfe\x8e\xfa\x91

  # Boolean values which indicated if the server is run in debug or testing mode.
  DEBUG: False
  TESTING: False

  # Boolean value which defines, if the access control should be used (True) or disabled (False)
  check_access_token: True

DEVELOPMENT: &development
  <<: *common

  check_access_token: False

  # IP address on which the API will be accessible. Normally this is 127.0.0.1
  # The port on which the API will listen
  api:
    host: 127.0.0.1
    port: 5001

  # Authentication for the MongoDB database.
  database:
    mongodb:
      database: test
      hostname: localhost
      port: 27017
      username: ""
      password: ""

      # Name of the collections in which data should be stored
      collection:
        property: z_rafael_properties
        ctrl_voc: z_rafael_ctrl_voc
        form: z_rafael_form
        user: z_rafael_user
        study: z_rafael_study

TESTING: &testing
  <<: *common
  DEBUG: False
  TESTING: True

  check_access_token: False

  api:
    host: 127.0.0.1
    port: 5001

  database:
    mongodb:
      database: test
      hostname: localhost
      port: 27017
      username: ""
      password: ""

      collection:
        property: z_rafael_testing_properties
        ctrl_voc: z_rafael_testing_ctrl_voc
        form: z_rafael_testing_form
        user: z_rafael_testing_user
        study: z_rafael_testing_study


PRODUCTION: &production
  <<: *common

  api:
    host: ""
    port: 5001

  database:
    mongodb:
      database: bioinfo
      hostname: rkaubmose021p.kau.roche.com
      port: 27017
      username: bioinfo
      password: bioinfo

      collection:
        property: property_service_properties
        ctrl_voc: property_service_ctrl_voc
        form: property_service_form
        user: property_service_user
        study: property_service_study

