
COMMON: &common
  app_secret: ""
  DEBUG: ""
  TESTING: ""

  check_access_token: ""

DEVELOPMENT: &development
  <<: *common

  check_access_token: ""

  api:
    host: ""
    port: ""

  database:
    mongodb:
      database: ""
      hostname: ""
      port: ""
      username: ""
      password: ""

      collection:
        property: ""
        ctrl_voc: ""
        form: ""
        user: ""
        study: ""

TESTING: &testing
  <<: *common
  DEBUG: ""
  TESTING: ""

  check_access_token: ""

  api:
    host: ""
    port: ""

  database:
    mongodb:
      database: ""
      hostname: ""
      port: ""
      username: ""
      password: ""

      collection:
        property: ""
        ctrl_voc: ""
        form: ""
        user: ""
        study: ""


PRODUCTION: &production
  <<: *common

  api:
    host: ""
    port: ""

  database:
    mongodb:
      database: ""
      hostname: ""
      port: ""
      username: ""
      password: ""

      collection:
        property: ""
        ctrl_voc: ""
        form: ""
        user: ""
        study: ""

